name: CustomArrows
version: '1'
main: me.xiaojibazhanshi.customarrows.CustomArrows
api-version: '1.21'
authors: [ XiaoJibaZhanshi ]
description: A custom arrow plugin
commands:
  customarrows:
    description: Lets you take some arrows
    usage: /customarrows
    aliases: [carrows]
